require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeptsupervisorsController do

  # This should return the minimal set of attributes required to create a valid
  # Deptsupervisor. As you add validations to Deptsupervisor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "firstname" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeptsupervisorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all deptsupervisors as @deptsupervisors" do
      deptsupervisor = Deptsupervisor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:deptsupervisors).should eq([deptsupervisor])
    end
  end

  describe "GET show" do
    it "assigns the requested deptsupervisor as @deptsupervisor" do
      deptsupervisor = Deptsupervisor.create! valid_attributes
      get :show, {:id => deptsupervisor.to_param}, valid_session
      assigns(:deptsupervisor).should eq(deptsupervisor)
    end
  end

  describe "GET new" do
    it "assigns a new deptsupervisor as @deptsupervisor" do
      get :new, {}, valid_session
      assigns(:deptsupervisor).should be_a_new(Deptsupervisor)
    end
  end

  describe "GET edit" do
    it "assigns the requested deptsupervisor as @deptsupervisor" do
      deptsupervisor = Deptsupervisor.create! valid_attributes
      get :edit, {:id => deptsupervisor.to_param}, valid_session
      assigns(:deptsupervisor).should eq(deptsupervisor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Deptsupervisor" do
        expect {
          post :create, {:deptsupervisor => valid_attributes}, valid_session
        }.to change(Deptsupervisor, :count).by(1)
      end

      it "assigns a newly created deptsupervisor as @deptsupervisor" do
        post :create, {:deptsupervisor => valid_attributes}, valid_session
        assigns(:deptsupervisor).should be_a(Deptsupervisor)
        assigns(:deptsupervisor).should be_persisted
      end

      it "redirects to the created deptsupervisor" do
        post :create, {:deptsupervisor => valid_attributes}, valid_session
        response.should redirect_to(Deptsupervisor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved deptsupervisor as @deptsupervisor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Deptsupervisor.any_instance.stub(:save).and_return(false)
        post :create, {:deptsupervisor => { "firstname" => "invalid value" }}, valid_session
        assigns(:deptsupervisor).should be_a_new(Deptsupervisor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Deptsupervisor.any_instance.stub(:save).and_return(false)
        post :create, {:deptsupervisor => { "firstname" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested deptsupervisor" do
        deptsupervisor = Deptsupervisor.create! valid_attributes
        # Assuming there are no other deptsupervisors in the database, this
        # specifies that the Deptsupervisor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Deptsupervisor.any_instance.should_receive(:update_attributes).with({ "firstname" => "MyString" })
        put :update, {:id => deptsupervisor.to_param, :deptsupervisor => { "firstname" => "MyString" }}, valid_session
      end

      it "assigns the requested deptsupervisor as @deptsupervisor" do
        deptsupervisor = Deptsupervisor.create! valid_attributes
        put :update, {:id => deptsupervisor.to_param, :deptsupervisor => valid_attributes}, valid_session
        assigns(:deptsupervisor).should eq(deptsupervisor)
      end

      it "redirects to the deptsupervisor" do
        deptsupervisor = Deptsupervisor.create! valid_attributes
        put :update, {:id => deptsupervisor.to_param, :deptsupervisor => valid_attributes}, valid_session
        response.should redirect_to(deptsupervisor)
      end
    end

    describe "with invalid params" do
      it "assigns the deptsupervisor as @deptsupervisor" do
        deptsupervisor = Deptsupervisor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Deptsupervisor.any_instance.stub(:save).and_return(false)
        put :update, {:id => deptsupervisor.to_param, :deptsupervisor => { "firstname" => "invalid value" }}, valid_session
        assigns(:deptsupervisor).should eq(deptsupervisor)
      end

      it "re-renders the 'edit' template" do
        deptsupervisor = Deptsupervisor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Deptsupervisor.any_instance.stub(:save).and_return(false)
        put :update, {:id => deptsupervisor.to_param, :deptsupervisor => { "firstname" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested deptsupervisor" do
      deptsupervisor = Deptsupervisor.create! valid_attributes
      expect {
        delete :destroy, {:id => deptsupervisor.to_param}, valid_session
      }.to change(Deptsupervisor, :count).by(-1)
    end

    it "redirects to the deptsupervisors list" do
      deptsupervisor = Deptsupervisor.create! valid_attributes
      delete :destroy, {:id => deptsupervisor.to_param}, valid_session
      response.should redirect_to(deptsupervisors_url)
    end
  end

end
