require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RosterCoordinatorsController do

  # This should return the minimal set of attributes required to create a valid
  # roster_coordinator. As you add validations to roster_coordinator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "firstname" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # roster_coordinatorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all roster_coordinators as @roster_coordinators" do
      roster_coordinator = RosterCoordinator.create! valid_attributes
      get :index, {}, valid_session
      assigns(:roster_coordinators).should eq([roster_coordinator])
    end
  end

  describe "GET show" do
    it "assigns the requested roster_coordinator as @roster_coordinator" do
      roster_coordinator = RosterCoordinator.create! valid_attributes
      get :show, {:id => roster_coordinator.to_param}, valid_session
      assigns(:roster_coordinator).should eq(roster_coordinator)
    end
  end

  describe "GET new" do
    it "assigns a new roster_coordinator as @roster_coordinator" do
      get :new, {}, valid_session
      assigns(:roster_coordinator).should be_a_new(RosterCoordinator)
    end
  end

  describe "GET edit" do
    it "assigns the requested roster_coordinator as @roster_coordinator" do
      roster_coordinator = RosterCoordinator.create! valid_attributes
      get :edit, {:id => roster_coordinator.to_param}, valid_session
      assigns(:roster_coordinator).should eq(roster_coordinator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RosterCoordinator" do
        expect {
          post :create, {:roster_coordinator => valid_attributes}, valid_session
        }.to change(RosterCoordinator, :count).by(1)
      end

      it "assigns a newly created roster_coordinator as @roster_coordinator" do
        post :create, {:roster_coordinator => valid_attributes}, valid_session
        assigns(:roster_coordinator).should be_a(RosterCoordinator)
        assigns(:roster_coordinator).should be_persisted
      end

      it "redirects to the created roster_coordinator" do
        post :create, {:roster_coordinator => valid_attributes}, valid_session
        response.should redirect_to(RosterCoordinator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved roster_coordinator as @roster_coordinator" do
        # Trigger the behavior that occurs when invalid params are submitted
        RosterCoordinator.any_instance.stub(:save).and_return(false)
        post :create, {:roster_coordinator => { "firstname" => "invalid value" }}, valid_session
        assigns(:roster_coordinator).should be_a_new(RosterCoordinator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RosterCoordinator.any_instance.stub(:save).and_return(false)
        post :create, {:roster_coordinator => { "firstname" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested roster_coordinator" do
        roster_coordinator = RosterCoordinator.create! valid_attributes
        # Assuming there are no other roster_coordinators in the database, this
        # specifies that the roster_coordinator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RosterCoordinator.any_instance.should_receive(:update_attributes).with({ "firstname" => "MyString" })
        put :update, {:id => roster_coordinator.to_param, :roster_coordinator => { "firstname" => "MyString" }}, valid_session
      end

      it "assigns the requested roster_coordinator as @roster_coordinator" do
        roster_coordinator = RosterCoordinator.create! valid_attributes
        put :update, {:id => roster_coordinator.to_param, :roster_coordinator => valid_attributes}, valid_session
        assigns(:roster_coordinator).should eq(roster_coordinator)
      end

      it "redirects to the roster_coordinator" do
        roster_coordinator = RosterCoordinator.create! valid_attributes
        put :update, {:id => roster_coordinator.to_param, :roster_coordinator => valid_attributes}, valid_session
        response.should redirect_to(roster_coordinator)
      end
    end

    describe "with invalid params" do
      it "assigns the roster_coordinator as @roster_coordinator" do
        roster_coordinator = RosterCoordinator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RosterCoordinator.any_instance.stub(:save).and_return(false)
        put :update, {:id => roster_coordinator.to_param, :roster_coordinator => { "firstname" => "invalid value" }}, valid_session
        assigns(:roster_coordinator).should eq(roster_coordinator)
      end

      it "re-renders the 'edit' template" do
        roster_coordinator = RosterCoordinator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RosterCoordinator.any_instance.stub(:save).and_return(false)
        put :update, {:id => roster_coordinator.to_param, :roster_coordinator => { "firstname" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested roster_coordinator" do
      roster_coordinator = RosterCoordinator.create! valid_attributes
      expect {
        delete :destroy, {:id => roster_coordinator.to_param}, valid_session
      }.to change(RosterCoordinator, :count).by(-1)
    end

    it "redirects to the roster_coordinators list" do
      roster_coordinator = RosterCoordinator.create! valid_attributes
      delete :destroy, {:id => roster_coordinator.to_param}, valid_session
      response.should redirect_to(roster_coordinators_url)
    end
  end

end
