require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VolschedulersController do

  # This should return the minimal set of attributes required to create a valid
  # Volscheduler. As you add validations to Volscheduler, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "job" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VolschedulersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all volschedulers as @volschedulers" do
      volscheduler = Volscheduler.create! valid_attributes
      get :index, {}, valid_session
      assigns(:volschedulers).should eq([volscheduler])
    end
  end

  describe "GET show" do
    it "assigns the requested volscheduler as @volscheduler" do
      volscheduler = Volscheduler.create! valid_attributes
      get :show, {:id => volscheduler.to_param}, valid_session
      assigns(:volscheduler).should eq(volscheduler)
    end
  end

  describe "GET new" do
    it "assigns a new volscheduler as @volscheduler" do
      get :new, {}, valid_session
      assigns(:volscheduler).should be_a_new(Volscheduler)
    end
  end

  describe "GET edit" do
    it "assigns the requested volscheduler as @volscheduler" do
      volscheduler = Volscheduler.create! valid_attributes
      get :edit, {:id => volscheduler.to_param}, valid_session
      assigns(:volscheduler).should eq(volscheduler)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Volscheduler" do
        expect {
          post :create, {:volscheduler => valid_attributes}, valid_session
        }.to change(Volscheduler, :count).by(1)
      end

      it "assigns a newly created volscheduler as @volscheduler" do
        post :create, {:volscheduler => valid_attributes}, valid_session
        assigns(:volscheduler).should be_a(Volscheduler)
        assigns(:volscheduler).should be_persisted
      end

      it "redirects to the created volscheduler" do
        post :create, {:volscheduler => valid_attributes}, valid_session
        response.should redirect_to(Volscheduler.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved volscheduler as @volscheduler" do
        # Trigger the behavior that occurs when invalid params are submitted
        Volscheduler.any_instance.stub(:save).and_return(false)
        post :create, {:volscheduler => { "job" => "invalid value" }}, valid_session
        assigns(:volscheduler).should be_a_new(Volscheduler)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Volscheduler.any_instance.stub(:save).and_return(false)
        post :create, {:volscheduler => { "job" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested volscheduler" do
        volscheduler = Volscheduler.create! valid_attributes
        # Assuming there are no other volschedulers in the database, this
        # specifies that the Volscheduler created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Volscheduler.any_instance.should_receive(:update_attributes).with({ "job" => "MyString" })
        put :update, {:id => volscheduler.to_param, :volscheduler => { "job" => "MyString" }}, valid_session
      end

      it "assigns the requested volscheduler as @volscheduler" do
        volscheduler = Volscheduler.create! valid_attributes
        put :update, {:id => volscheduler.to_param, :volscheduler => valid_attributes}, valid_session
        assigns(:volscheduler).should eq(volscheduler)
      end

      it "redirects to the volscheduler" do
        volscheduler = Volscheduler.create! valid_attributes
        put :update, {:id => volscheduler.to_param, :volscheduler => valid_attributes}, valid_session
        response.should redirect_to(volscheduler)
      end
    end

    describe "with invalid params" do
      it "assigns the volscheduler as @volscheduler" do
        volscheduler = Volscheduler.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Volscheduler.any_instance.stub(:save).and_return(false)
        put :update, {:id => volscheduler.to_param, :volscheduler => { "job" => "invalid value" }}, valid_session
        assigns(:volscheduler).should eq(volscheduler)
      end

      it "re-renders the 'edit' template" do
        volscheduler = Volscheduler.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Volscheduler.any_instance.stub(:save).and_return(false)
        put :update, {:id => volscheduler.to_param, :volscheduler => { "job" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested volscheduler" do
      volscheduler = Volscheduler.create! valid_attributes
      expect {
        delete :destroy, {:id => volscheduler.to_param}, valid_session
      }.to change(Volscheduler, :count).by(-1)
    end

    it "redirects to the volschedulers list" do
      volscheduler = Volscheduler.create! valid_attributes
      delete :destroy, {:id => volscheduler.to_param}, valid_session
      response.should redirect_to(volschedulers_url)
    end
  end

end
